# Rewrite calculate distance using NumPy

In [5]:
import math

import numpy as np

def calculate_distance(coord1, coord2, box_length=None):
    """
    Calculate the distance between two 3D coordinates.
    
    Parameters
    ----------
    coord1, coord2: list
        The atomic coordinates
    
    Returns
    -------
    distance: float
        The distance between the two points.
    """
    
    distance = 0
    for i in range(3):
        dim_dist = (coord1[i] - coord2[i]) 
        
        if box_length:
            dim_dist = dim_dist - box_length * round(dim_dist / box_length)
        
        dim_dist = dim_dist**2
        distance += dim_dist
    
    distance = math.sqrt(distance)
    return distance


In [6]:
point1 = [0, 0, 0]
point2 = [0, 1, 0]

calculate_distance(point1, point2)

1.0

In [7]:
point1 = np.array([0, 0, 0])
point2 = np.array([0, 1, 0])

calculate_distance(point1, point2)

1.0

In [38]:
def calculate_distance_np(coord1, coord2, box_length=None):
    """
    Calculate the distance between two 3D coordinates.
    
    Parameters
    ----------
    coord1, coord2: np.ndarray
        The atomic coordinates
    
    Returns
    -------
    distance: np.ndarray
        The distance between particles.
    """
    
    coord_dist = coord1 - coord2
    
    if box_length:
        coord_dist = coord_dist - box_length * np.round(coord_dist / box_length)
        
    if coord_dist.ndim < 2:
        coord_dist = coord_dist.reshape(1, 3)
    
    coord_dist = coord_dist ** 2
    
    coord_dist_sum = coord_dist.sum(axis=1)
    
    distance = np.sqrt(coord_dist_sum)
    
    return distance

In [39]:
calculate_distance_np(point1, point2, 10)

array([1.])

In [40]:
coord_set1 = np.array([[0, 0, 0], [0, 1, 0]])
coord_set2 = np.array([[0, 8, 0], [0, 1.5, 0]])

# Want to get two distances
calculate_distance_np(coord_set1, coord_set2, 10)

array([2. , 0.5])

In [41]:
calculate_distance_np(coord_set1[0], coord_set2)

array([8. , 1.5])

In [37]:
point1.reshape(1, -1)

array([[0, 0, 0]])

In [33]:
point1.ndim

1

In [50]:
coord_set1 = np.array([[1, 2, 3], [4, 5, 6]])
coord_set1.reshape(3, -1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
coord_set1

array([[1, 2, 3],
       [4, 5, 6]])