# Intro to NumPy Arrays

In [1]:
import numpy as np
import math

In [3]:
# Construct some coordinates
coordinates = [[0, 0, 0], [0, 0, math.pow(2, 1/6)], [0, 0, 2*math.pow(2, 1/6)], [0, math.pow(2, 1/6), 0]]

second_coordinate = coordinates[1]

In [5]:
translation_vector = [0.1, -0.1, 0]

new_coordinate = []
for i in range(3):
    translated_coordinate = second_coordinate[i] + translation_vector[i]
    new_coordinate.append(translated_coordinate)

In [6]:
# Create a numpy array from a list
second_coordinate_np = np.array(second_coordinate)

# Create a numpy array from a list
translation_vector_np = np.array(translation_vector)

In [10]:
new_coordinate_np = second_coordinate_np + translation_vector_np

In [11]:
print(new_coordinate_np)

[ 0.1        -0.1         1.12246205]


In [13]:
type(new_coordinate_np)

numpy.ndarray

In [14]:
second_coordinate + translation_vector

[0, 0, 1.122462048309373, 0.1, -0.1, 0]

In [15]:
# Access array shape
second_coordinate_np.shape

(3,)

In [16]:
# Access the number of dimensions
second_coordinate_np.ndim

1

In [17]:
coordinates_np = np.array(coordinates)

In [18]:
coordinates_np.shape

(4, 3)

In [19]:
coordinates_np.ndim

2

In [21]:
# accessing information in multidimensional array vs python list

# access y coordinate of first atom
coordinates[0][1]

# access y coordinate of first atom in NumPy array
coordinates_np[0, 1]

0.0

## Broadcasting

In [22]:
# Translate our molecule
new_coordinates_np = coordinates_np + translation_vector

print(new_coordinates_np)

[[ 0.1        -0.1         0.        ]
 [ 0.1        -0.1         1.12246205]
 [ 0.1        -0.1         2.2449241 ]
 [ 0.1         1.02246205  0.        ]]


In [23]:
new_coordinates_np.shape

(4, 3)

In [24]:
translation_vector_np.shape

(3,)

In [26]:
# Can do logical comparisons
coordinates_np > 0

array([[False, False, False],
       [False, False,  True],
       [False, False,  True],
       [False,  True, False]])

In [28]:
# using logical comparison as index into array
greater_than_zero_values = coordinates_np[coordinates_np > 0]

In [29]:
coordinates_np.shape

(4, 3)

In [31]:
coordinates_np.mean(axis=0)

array([0.        , 0.28061551, 0.84184654])

In [35]:
coordinates_np[:, 1]

array([0.        , 0.        , 0.        , 1.12246205])

In [ ]:
# Break for 15ish minutes - be back at 36 minutes after the hour.